version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-minor-patch:
        update-types: ["minor", "patch"]
