import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

/**
 * ESLint flat config (#198).
 *
 * Two enforcement rules drive this config:
 *
 *   no-restricted-imports (pattern: "../*")
 *     Bans any literal `../` import string. Sibling-folder imports
 *     (`./X`) still allowed; aliases (@app/@shared/@features/@engine/
 *     @theme/@storage) are allowed because they don't literally start
 *     with `../`. Pairs with tsconfig.app.json + tsconfig.json paths.
 *     Eliminates the `../../../` churn that dominated #196 and #197.
 *
 *     Why not `import/no-relative-parent-imports`? That rule resolves
 *     imports to absolute paths and flags any that land in a parent
 *     directory — which catches alias imports too (e.g. `@engine/types`
 *     from `src/shared/game/components/...` resolves to a parent dir).
 *     The literal-syntax check is what we actually want.
 *
 *   import/no-restricted-paths
 *     Encodes Bulletproof React's architectural zones:
 *       - No cross-feature imports (features/X cannot import from
 *         features/Y).
 *       - Unidirectional layering: `shared → features → app`.
 *         shared/engine/theme/storage cannot import from features/app.
 *
 * Playwright specs at frontend/playwright/ are exempt from the alias
 * rule — their `../test-helpers/X` imports are tiny intra-playwright
 * hops and adding a test-helpers alias to tsconfig.json is more
 * complexity than it's worth today. Aliases are still resolvable from
 * Playwright via tsconfig.json's paths block, so future specs
 * importing src/ can use @shared/X etc.
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'public/**',
      // Generated by Vite/Vitest cache
      '.vite/**',
    ],
  },

  // Base JS rules
  js.configs.recommended,

  // TypeScript rules (non-type-checked variant — the project already
  // runs `tsc -b` separately for full type-checking; ESLint focuses on
  // structural rules here for speed.)
  ...tseslint.configs.recommended,

  // Project-wide rules for all TS/TSX
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      import: importPlugin,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: 'detect' },
      'import/resolver': {
        // typescript resolver follows tsconfig paths so the import
        // plugin understands @app/@shared/etc. references. Listing only
        // tsconfig.app.json (which covers src/ — where almost all
        // imports live) avoids the "Multiple projects found" warning
        // from eslint-import-resolver-typescript. tsconfig.json's paths
        // map is identical and only used by Playwright's esbuild, which
        // isn't linted here.
        typescript: {
          project: './tsconfig.app.json',
        },
      },
    },
    linterOptions: {
      // Flag stale `// eslint-disable-next-line X` comments where X is
      // never reported. Prevents disable-comment rot (e.g. the inert
      // `// eslint-disable-next-line no-console` removed from
      // src/app/providers.tsx in #198).
      reportUnusedDisableDirectives: 'warn',
    },
    rules: {
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      // Standard convention: vars/args prefixed with `_` are
      // deliberately unused (often function-signature compliance with
      // an interface). typescript-eslint's recommended preset doesn't
      // configure this by default.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Classic hooks rules only. eslint-plugin-react-hooks@7's
      // `recommended` preset adds new React-Compiler-aware rules
      // (`react-hooks/purity`, `react-hooks/refs`, etc.) that flag
      // pre-existing patterns in the codebase (e.g. `Date.now()` during
      // render). Adopting them is out of scope for #198 (path aliases +
      // ESLint enforcement); file a follow-up to enable + fix sites.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // We don't use prop-types in TS; React.configs.recommended turns
      // this on by default.
      'react/prop-types': 'off',

      // The three enforcement rules this PR introduces.
      // Bans cross-folder relative imports. `./X` (within-folder
      // sibling) still allowed; `./X/Y` (subfolder hop) banned; any
      // `../` banned. Aliases (start with `@`) are allowed.
      // The companion `no-restricted-syntax` rule below extends this
      // ban to vitest's module-mock string-literal args (vi.mock,
      // vi.importActual, etc.) which `no-restricted-imports` does NOT
      // inspect.
      'no-restricted-syntax': [
        'error',
        {
          // Matches paths starting with `../` (parent-relative) OR
          // `./<something>/` (cross-folder relative). Bare `./X`
          // sibling-file mocks stay allowed, matching the
          // no-restricted-imports policy.
          selector:
            "CallExpression[callee.object.name='vi'][callee.property.name=/^(mock|doMock|unmock|importActual|importMock)$/] > Literal[value=/^\\.\\.\\/|^\\.\\/[^/]+\\//]",
          message:
            "vi.mock / vi.importActual / etc. must use a path alias (@layer/X), not a relative path. The lint rule above doesn't catch these calls because they aren't import statements.",
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../*', './*/*'],
              message:
                'Use a path alias (@app/@shared/@features/@engine/@theme/@storage; transitional: @pages/@components/@hooks/@services) instead of a cross-folder relative import. See tsconfig.app.json paths + frontend/CLAUDE.md.',
            },
          ],
        },
      ],
      'import/no-restricted-paths': [
        'error',
        {
          zones: [
            // No cross-feature imports. Add one zone per feature folder
            // that exists today. When a new feature folder lands, add
            // its zone here.
            {
              target: './src/features/admin',
              from: './src/features',
              except: ['./admin'],
            },
            {
              target: './src/features/daily',
              from: './src/features',
              except: ['./daily'],
            },
            {
              target: './src/features/curation',
              from: './src/features',
              except: ['./curation'],
            },
            {
              target: './src/features/landing',
              from: './src/features',
              except: ['./landing'],
            },

            // Unidirectional: shared → features → app.
            // Features cannot import from app (app composes features).
            { target: './src/features', from: './src/app' },
            // Shared cannot import from features or app.
            {
              target: './src/shared',
              from: ['./src/features', './src/app'],
            },
            // Engine is pure domain — nothing react/feature/app.
            {
              target: './src/engine',
              from: ['./src/features', './src/app', './src/shared'],
            },
            // Theme is design tokens — features/app are above it.
            {
              target: './src/theme',
              from: ['./src/features', './src/app'],
            },
            // Storage is IndexedDB plumbing.
            {
              target: './src/storage',
              from: ['./src/features', './src/app'],
            },
          ],
        },
      ],
    },
  },

  // Playwright specs: relax the alias rule (intra-playwright relative
  // imports are fine; aliases still work for imports into src/).
  {
    files: ['playwright/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },

  // Vite/Tamagui/Playwright config files run under Node — give them
  // Node globals and relax React-specific rules.
  {
    files: [
      'vite.config.ts',
      'vitest.config.ts',
      'tamagui.config.ts',
      'playwright.config.ts',
      'eslint.config.js',
      'scripts/**/*.{js,ts,mjs}',
    ],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // Tamagui module-merging convention: the `TamaguiCustomConfig`
  // interface deliberately declares no members so consumers can augment
  // it via TypeScript declaration merging (per Tamagui's `createTamagui`
  // docs). The empty-object-type rule is the wrong fit here.
  {
    files: ['tamagui.config.ts'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
);
