services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_TOKEN}
    volumes:
      - ./.localstack:/etc/localstack/init/ready.d
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
