// This test implements the N-feasibility probe described in
// openspec/changes/phase-5-generator-rework/input-spec.md §4.1 and
// specs/puzzle-generation.md PG-04.
//
// TestFeasibility runs the sampler at every (N in {4..8}, k in {1, 2}) for a
// fixed 5-second wall-clock budget per case, counts distinct solutions
// produced, and emits a summary table.
//
// The test is skipped under `go test -short` so the regular fast test suite
// is unaffected. The full test suite runs it (adding ~50s wall-clock).
//
// Output handling (important for a clean working tree in CI and for other
// contributors):
//   - By default, the table is written to a per-test TempDir and logged.
//     The committed bench/n-feasibility.md snapshot is NOT modified.
//   - Set UPDATE_BENCH=1 to refresh the committed snapshot. This path is
//     intended for the author running the probe on a known-stable machine;
//     the snapshot includes samples/sec numbers that depend on the host CPU.

package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"
)

func TestFeasibility(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping N-feasibility probe in -short mode")
	}

	const budget = 5 * time.Second

	var rows []feasibilityRow
	ns := []int{4, 5, 6, 7, 8}
	ks := []int{1, 2}

	for _, k := range ks {
		for _, n := range ns {
			g, err := New(n, k, WithSeed(int64(n*100+k)))
			if err != nil {
				rows = append(rows, feasibilityRow{N: n, K: k})
				continue
			}
			seen := make(map[string]struct{}, 1024)
			samples := 0
			start := time.Now()
			for time.Since(start) < budget {
				marks, ok := g.sampleSolution()
				samples++
				if !ok {
					continue
				}
				seen[fingerprint(marks)] = struct{}{}
			}
			elapsed := time.Since(start).Seconds()
			rows = append(rows, feasibilityRow{
				N:          n,
				K:          k,
				Samples:    samples,
				Distinct:   len(seen),
				SamplesPer: float64(samples) / elapsed,
			})
		}
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].K != rows[j].K {
			return rows[i].K < rows[j].K
		}
		return rows[i].N < rows[j].N
	})

	var md strings.Builder
	md.WriteString("# N-feasibility probe (R-063)\n\n")
	md.WriteString("Generated by `TestFeasibility`. Each (N, k) cell ran the Solution\n")
	md.WriteString("Sampler for 5 seconds wall-clock and counted distinct placements.\n\n")
	md.WriteString("| N | k | samples/sec | distinct solutions in 5s |\n")
	md.WriteString("|---|---|-------------|--------------------------|\n")
	for _, r := range rows {
		md.WriteString(fmt.Sprintf("| %d | %d | %.0f | %d |\n",
			r.N, r.K, r.SamplesPer, r.Distinct))
	}
	md.WriteString("\n")
	md.WriteString("## Interpretation\n\n")
	md.WriteString(recommendation(rows))
	md.WriteString("\n")

	// Emit to the committed snapshot only when explicitly requested; otherwise
	// write to a temp dir so a regular `go test ./...` leaves a clean tree.
	var outPath string
	if os.Getenv("UPDATE_BENCH") == "1" {
		const outDir = "bench"
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			t.Fatalf("creating bench dir: %v", err)
		}
		outPath = filepath.Join(outDir, "n-feasibility.md")
	} else {
		outPath = filepath.Join(t.TempDir(), "n-feasibility.md")
	}
	if err := os.WriteFile(outPath, []byte(md.String()), 0o644); err != nil {
		t.Fatalf("writing %s: %v", outPath, err)
	}
	t.Logf("wrote %s (set UPDATE_BENCH=1 to refresh bench/n-feasibility.md)", outPath)

	// Soft gate: the probe must have attempted every cell, and at least one
	// (N, k=1) cell in [5..8] must be productive. We do NOT fail on k=2
	// starvation at low N — locked decisions #3 acknowledges that k=2 has
	// its own tighter floor (empirically N>=8 per the sampler tests).
	foundK1 := false
	for _, r := range rows {
		if r.K == 1 && r.N >= 5 && r.Distinct > 0 {
			foundK1 = true
			break
		}
	}
	if !foundK1 {
		t.Fatalf("no k=1 cell with N>=5 produced any distinct solutions — sampler is broken")
	}
}

type feasibilityRow struct {
	N          int
	K          int
	Samples    int
	Distinct   int
	SamplesPer float64
}

// recommendation inspects the probe data and emits a short prose summary
// that justifies (or challenges) the interim NMin=5 package constant.
func recommendation(rows []feasibilityRow) string {
	// Find the smallest N with k=1 that produced >= 10 distinct solutions
	// in the 5s budget — the heuristic the task names for the N_min floor.
	var minN1 int
	for _, r := range rows {
		if r.K == 1 && r.Distinct >= 10 {
			if minN1 == 0 || r.N < minN1 {
				minN1 = r.N
			}
		}
	}
	var b strings.Builder
	b.WriteString("- NMin is interim-locked at 5 (proposal AC-10). ")
	switch {
	case minN1 == 0:
		b.WriteString("No k=1 cell produced >=10 distinct solutions; NMin=5 is above what the probe could verify at low N. ")
	case minN1 <= 5:
		b.WriteString("k=1 produces >=10 distinct solutions at N=5, consistent with NMin=5. ")
	default:
		b.WriteString(fmt.Sprintf("k=1 first crosses >=10 distinct solutions at N=%d; consider raising NMin.\n", minN1))
	}
	b.WriteString("k=2 is empirically infeasible for N<8 (see TestSampleConstraints' minFeasibleN map). ")
	b.WriteString("The orchestrator in R-065 should reject k=2 requests below N=8 with a typed error.\n")
	return b.String()
}
