output "api_gateway_invoke_url" {
  description = "API Gateway invoke URL"
  value       = aws_api_gateway_stage.api.invoke_url
}

output "api_gateway_domain" {
  description = "API Gateway domain name (without protocol or stage)"
  value       = "${aws_api_gateway_rest_api.api.id}.execute-api.${data.aws_region.current.name}.amazonaws.com"
}

output "api_gateway_stage" {
  description = "API Gateway stage name"
  value       = aws_api_gateway_stage.api.stage_name
}

output "clerk_publishable_key_param_name" {
  description = "SSM Parameter Store name for the Clerk publishable key. The CD workflow reads this at frontend build time."
  value       = aws_ssm_parameter.clerk_publishable_key.name
}

output "clerk_secret_key_param_name" {
  description = "SSM Parameter Store name for the Clerk secret key. The Lambda fetches this at startup via auth.LoadClerkSecret."
  value       = aws_ssm_parameter.clerk_secret_key.name
}

output "client_api_key_value" {
  description = "Browser-distributed API key bound to the client usage plan. Auto-generated by AWS. The CD workflow reads it at frontend build time and bakes it into the bundle as VITE_API_KEY."
  value       = aws_api_gateway_api_key.client.value
  sensitive   = true
}
