package generator

import (
	"testing"
	"time"
)

// deducibleRegionMap5x5 is a 5x5 region map known to be solvable without
// backtracking. Solution: (0,0),(1,2),(2,4),(3,1),(4,3).
var deducibleRegionMap5x5 = [][]int{
	{2, 2, 4, 4, 4},
	{2, 1, 1, 4, 4},
	{1, 1, 3, 3, 4},
	{0, 0, 3, 3, 3},
	{0, 0, 3, 3, 3},
}

// TestIsLogicallyDeducible_KnownDeducible verifies that a puzzle solvable
// without backtracking returns true.
func TestIsLogicallyDeducible_KnownDeducible(t *testing.T) {
	// Arrange
	regionMap := deducibleRegionMap5x5

	// Act
	result := IsLogicallyDeducible(regionMap, 5, 1)

	// Assert
	if !result {
		t.Error("expected deducibleRegionMap5x5 to be logically deducible, got false")
	}
}

// TestIsLogicallyDeducible_NonDeducible verifies that a puzzle with a unique
// solution but requiring backtracking returns false.
func TestIsLogicallyDeducible_NonDeducible(t *testing.T) {
	// Arrange
	// validRegionMap5x5 has unique solution (0,2),(1,0),(2,3),(3,1),(4,4) but
	// the deterministic row-by-row search must backtrack to find it —
	// the first candidate tried in row 0 leads to a dead end.
	regionMap := validRegionMap5x5

	// Confirm uniqueness so this test is meaningful.
	solver := NewPropagationSolver()
	count := solver.CountSolutions(regionMap, 5, 1, 2)
	if count != 1 {
		t.Fatalf("expected unique solution, got %d solutions", count)
	}

	// Act
	result := IsLogicallyDeducible(regionMap, 5, 1)

	// Assert
	if result {
		t.Error("expected validRegionMap5x5 to NOT be logically deducible, got true")
	}
}

// TestIsLogicallyDeducible_Contradiction verifies that a region map with no
// valid solution returns false.
func TestIsLogicallyDeducible_Contradiction(t *testing.T) {
	// Arrange
	// 3x3 column-stripe regions: impossible due to adjacency constraints.
	regionMap := [][]int{
		{0, 1, 2},
		{0, 1, 2},
		{0, 1, 2},
	}

	// Act
	result := IsLogicallyDeducible(regionMap, 3, 1)

	// Assert
	if result {
		t.Error("expected impossible grid to return false, got true")
	}
}

// TestIsLogicallyDeducible_DoubleQueens verifies deducibility check works with
// markersPerUnit > 1.
func TestIsLogicallyDeducible_DoubleQueens(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping Double Queens deducibility test in short mode")
	}

	// Arrange
	// Row-stripe 8x8 with markersPerUnit=2 has multiple solutions — not deducible.
	regionMap := make([][]int, 8)
	for r := 0; r < 8; r++ {
		regionMap[r] = make([]int, 8)
		for c := 0; c < 8; c++ {
			regionMap[r][c] = r
		}
	}

	// Act
	result := IsLogicallyDeducible(regionMap, 8, 2)

	// Assert
	if result {
		t.Error("expected row-stripe 8x8 Double Queens to NOT be logically deducible, got true")
	}
}

// TestGeneratedPuzzles_AreLogicallyDeducible verifies that puzzles generated by
// each pipeline pass the deducibility check. This test runs after the pipelines
// have the deducibility gate integrated.
func TestGeneratedPuzzles_AreLogicallyDeducible(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping generated puzzle deducibility test in short mode")
	}

	pipelines := []struct {
		name     string
		pipeline PipelineStrategy
	}{
		{
			name:     "RegionFirst",
			pipeline: NewRegionFirstPipeline(NewPropagationSolver()),
		},
		{
			name:     "IterativeRefinement",
			pipeline: NewIterativeRefinementPipeline(NewPropagationSolver(), NewBFSRegionGenerator()),
		},
		{
			name:     "ConstraintAware",
			pipeline: NewConstraintAwarePipeline(NewPropagationSolver()),
		},
	}

	for _, pp := range pipelines {
		t.Run(pp.name, func(t *testing.T) {
			// Arrange
			opts := GenerateOpts{Timeout: 60 * time.Second, Deducible: true}

			// Act
			puzzle, err := pp.pipeline.Generate(5, 1, opts)

			// Assert
			if err != nil {
				t.Fatalf("Generate returned error: %v", err)
			}
			if !IsLogicallyDeducible(puzzle.RegionMap, puzzle.GridSize, 1) {
				t.Error("generated puzzle is NOT logically deducible")
			}
		})
	}
}

// BenchmarkIsLogicallyDeducible_5x5 measures the cost of the deducibility check.
func BenchmarkIsLogicallyDeducible_5x5(b *testing.B) {
	// Arrange
	regionMap := validRegionMap5x5

	// Act
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		IsLogicallyDeducible(regionMap, 5, 1)
	}
}
